# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-25 18:45
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSerie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(verbose_name='length')),
                ('curve', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='curve')),
                ('data', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None, verbose_name='data')),
                ('probabilities', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None, verbose_name='probabilities')),
            ],
        ),
        migrations.CreateModel(
            name='ResamplingSerie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_serie_id', models.IntegerField(verbose_name='base_serie')),
                ('length', models.IntegerField(verbose_name='length')),
                ('curve', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='curve')),
                ('data', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None, verbose_name='data')),
                ('probabilities', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None, verbose_name='probabilities')),
                ('estimator', models.CharField(blank=True, choices=[('lmom', 'L-Moments'), ('mlh', 'Maximum Likely-Hood')], max_length=5, verbose_name='estimator')),
            ],
        ),
    ]
